version: "3"

services:
  portainer: # Used as the hostname for the Proxy host in NPM
    image: 'portainer/portainer-ce:latest'
    restart: unless-stopped
    volumes:
      - ./volumes/portainer_data:/data 
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - frontend 

networks:
  frontend:
    external: true
    name: home-server 
