version: '3.3'

services:
  fireflyiii:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    depends_on:
      - db
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.fireflyiii.rule=Host(`fireflyiii.dfhssilva.xyz`)
      - traefik.http.routers.fireflyiii.entrypoints=websecure
      - traefik.http.routers.fireflyiii.tls.certresolver=myresolver

  db:
    image: linuxserver/mariadb:latest
    hostname: fireflyiiidb
    restart: always
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - backend

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  frontend:
    external: true
    name: home-server
  backend: