version: '3.3'

services:
  fireflyiii:
    image: fireflyiii/core:latest
    restart: unless-stopped
    volumes:
      - ./fireflyiii-upload:/var/www/html/storage/upload
    env_file: .env
    depends_on:
      - db
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.fireflyiii.rule=Host(`fireflyiii.dfhssilva.xyz`)
      - traefik.http.routers.fireflyiii.entrypoints=websecure
      - traefik.http.routers.fireflyiii.tls.certresolver=myresolver

  db:
    image: linuxserver/mariadb:latest
    hostname: fireflyiiidb
    restart: unless-stopped
    env_file: .db.env
    volumes:
      - ./fireflyiii-db:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - backend

networks:
  frontend:
    external: true
    name: home-server
  backend: