version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    command: 
      #- "--log.level=DEBUG"  # Uncomment to test/debug
      # Traefik will listen on port 8080 by default for API request
      - "--api.insecure=true"
      # Enabling docker provider
      - "--providers.docker"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # Traefik will listen to incoming request on the port 443 (https)
      - "--entrypoints.websecure.address=:443"
      # Enable a tls challenge named "myresolver"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      # Tell it to use our predefined entrypoint named "web"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"  # Uncomment to test/debug
      # The email to provide to let's encrypt
      - "--certificatesresolvers.myresolver.acme.email=dfhssilva@protonmail.com"
      # Tell to store the certificate on a path under our volume
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # Create a letsencrypt dir within the folder where the docker-compose file is
      - ./letsencrypt:/letsencrypt
      # So that Traefik can read the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend 

networks:
  frontend:
    external: true
    name: home-server 