version: "3"

services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    volumes:
      - ./nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_db
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_HOST=nextcloud-db
      - OVERWRITEPROTOCOL=https
    secrets:
      - mysql_db
      - mysql_password
      - mysql_user
    depends_on:
      - nextcloud-db
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.dfhssilva.xyz`)
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.tls.certresolver=myresolver

  nextcloud-db:
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    volumes:
      - ./nextcloud-db:/config
    environment:
      - PUID=1000
      - PGID=1000
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
      - TZ=Europe/London
      - FILE__MYSQL_PASSWORD=/run/secrets/mysql_password
      - FILE__MYSQL_DATABASE=/run/secrets/mysql_db
      - FILE__MYSQL_USER=/run/secrets/mysql_user
    secrets:
      - mysql_db
      - mysql_password
      - mysql_root_password
      - mysql_user
    networks:
      - backend

networks:
  frontend:
    external: true
    name: home-server
  backend:

secrets:
  mysql_db:
    file: ./nextcloud_mysql_db.txt
  mysql_root_password:
    file: ./nextcloud_mysql_root_password.txt
  mysql_password:
    file: ./nextcloud_mysql_password.txt
  mysql_user:
    file: ./nextcloud_mysql_user.txt
