version: "3"

services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    restart: unless-stopped
    volumes:
      - ./portainer_data:/data 
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - frontend 

networks:
  frontend:
    external: true
    name: home-server 
